trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: "adservice cartservice/src checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice"

stages:
  - stage: Terraform
    displayName: 'Terraform Deployment'
    jobs:
      - job: Init
        displayName: 'Terraform Init Job'
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                cd /home/ubuntu/myagent/_work/3/s/Private_AKS
                echo "Initializing Terraform..."
                terraform init
            displayName: 'Terraform Init'
          
          - task: CmdLine@2
            inputs:
              script: |
                cd /home/ubuntu/myagent/_work/3/s/Private_AKS
                echo "Planning Terraform..."
                terraform plan -out=tfplan
            displayName: 'Terraform Plan'

          - task: CmdLine@2
            inputs:
              script: |
                cd /home/ubuntu/myagent/_work/3/s/Private_AKS
                echo "Applying Terraform..."
                terraform destroy --auto-approve
            displayName: 'Terraform Apply'
