trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan' # Managed node pool name

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: 'cloudops96/public'
        command: 'buildAndPush'
        Dockerfile: '**/src/adservice/Dockerfile'
        tags: 'adservice'
        addPipelineData: false
        addBaseImageData: false