trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build Docker Images
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Azure_Container_Registory_connection'
              repository: 'cartservice'
              command: 'buildAndPush'
              Dockerfile: 'src/cartservice/src/Dockerfile'
              tags: 'latest'
              addPipelineData: false
              addBaseImageData: false

