trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: "adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice"

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        steps:
          - script: |
              # Login to ACR
              az acr login --name chandancloudops96

              # Build and push Docker images
              for service in $(services); do
                echo "Building and pushing Docker image for $service"
                if [ "$service" = "cartservice" ]; then
                  docker build -t chandancloudops96.azurecr.io/$service -f cartservice/src/Dockerfile .
                else
                  docker build -t chandancloudops96.azurecr.io/$service -f src/$service/Dockerfile .
                fi
                docker push chandancloudops96.azurecr.io/$service
              done
            displayName: 'Build and Push Docker Images'
            env:
              DOCKER_BUILDKIT: 0
