trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: "adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice"

stages:
  - stage: Terraform
    displayName: 'Terraform Deployment'
    jobs:
      - job: Init
        displayName: 'Terraform Init Job'
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                cd /home/ubuntu/myagent/_work/3/s/Private_AKS
                echo "Initializing Terraform..."
                terraform init
            displayName: 'Terraform Init'
          
          - task: CmdLine@2
            inputs:
              script: |
                cd /home/ubuntu/myagent/_work/3/s/Private_AKS
                echo "Planning Terraform..."
                terraform plan -out=tfplan
            displayName: 'Terraform Plan'

          - task: CmdLine@2
            inputs:
              script: |
                cd /home/ubuntu/myagent/_work/3/s/Private_AKS
                echo "Applying Terraform..."
                terraform apply --auto-approve
            displayName: 'Terraform Apply'

  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    dependsOn: Terraform
    jobs:
      - job: Build
        displayName: Build
        steps:
          - script: |
              # Login to ACR
              az acr login --name chandancloudops96

              # Build and push Docker images
              for service in $(services); do
                echo "Building and pushing Docker image for $service"
                docker build -t chandancloudops96.azurecr.io/$service -f src/$service/Dockerfile .
                docker push chandancloudops96.azurecr.io/$service
              done
            displayName: 'Build and Push Docker Images'
            env:
              DOCKER_BUILDKIT: 1
