trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build Docker Images
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'Azure_Container_Registory_connection'  # Replace with your service connection name
              repository: 'chandancloudops96/cartservice'  # Specify the full repository path
              command: 'buildAndPush'
              Dockerfile: 'src/cartservice/src/Dockerfile'  # Correct Dockerfile path
              tags: 'latest'  # Use 'latest' or other specific tags as needed
              addPipelineData: false
              addBaseImageData: false

