trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: "adservice cartservice checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingassistantservice"

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build
        steps:
          - script: |
              # Login to ACR
              az acr login --name chandancloudops96

              # Echo the services variable for debugging
              echo "Services to build: $services"

              # Build and push Docker images
              for service in $services; do
                echo "Building and pushing Docker image for $service"
                
                # Adjust the Dockerfile path for cartservice
                if [ "$service" == "cartservice" ]; then
                  docker build -t chandancloudops96.azurecr.io/$service -f src/cartservice/src/Dockerfile src/cartservice
                else
                  docker build -t chandancloudops96.azurecr.io/$service -f src/$service/Dockerfile src/$service
                fi
                
                # Check if the build was successful before pushing
                if [ $? -eq 0 ]; then
                  docker push chandancloudops96.azurecr.io/$service
                else
                  echo "Failed to build $service, skipping push."
                fi
              done
            displayName: 'Build and Push Docker Images'
