trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'Chandan'  # Managed node pool name

variables:
  services: 'adservice cartservice/src checkoutservice currencyservice emailservice frontend loadgenerator paymentservice productcatalogservice recommendationservice shippingservice shoppingassistantservice'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build Docker Images
        steps:
          # Loop through each service to build and push Docker images
          - ${{ each service in split(variables.services, ' ') }}:
              - task: Docker@2
                inputs:
                  containerRegistry: 'Azure_Container_Registory_connection'  # Your service connection name
                  repository: '${{ service }}'  # Repository name for the service
                  command: 'buildAndPush'
                  Dockerfile: 'src/${{ service }}/Dockerfile'  # Path to Dockerfile for the service
                  tags: 'latest'
                  addPipelineData: false
                  addBaseImageData: false
